sudo: required
services:
  - docker

before_install:
  - docker build -t sornik/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sornik/react-test npm test

after_success:
  - docker build -t sornik/multi-client ./client
  - docker build -t sornik/multi-nginx ./nginx
  - docker build -t sornik/multi-server ./server
  - docker build -t sornik/multi-worker ./worker
